xiamiBoard.initXiaMiBoard()
xiamiBoard.OLEDclear()
xiamiBoard.tempHumiInit(SENSOR.SHTC3)
basic.forever(function () {
    led.plot(0, 0)
    pins.servoSetPulse(AnalogPin.P8, 2000)
    basic.pause(5000)
    led.plot(1, 0)
    pins.servoSetPulse(AnalogPin.P8, 2100)
    basic.pause(5000)
    led.plot(2, 0)
    pins.servoSetPulse(AnalogPin.P8, 2200)
    basic.pause(5000)
    led.plot(3, 0)
    pins.servoSetPulse(AnalogPin.P8, 2300)
    basic.pause(5000)
    led.plot(4, 0)
    pins.servoSetPulse(AnalogPin.P8, 2400)
    basic.pause(5000)
    basic.clearScreen()
})
