xiamiBoard.initXiaMiBoard()
xiamiBoard.OLEDclear()
xiamiBoard.tempHumiInit(SENSOR.SHTC3)
basic.forever(function () {
    led.plot(0, 0)
    pins.servoSetPulse(AnalogPin.P8, 1000)
    xiamiBoard.setRelay(RELAYVERSION.V2, RELAY.CLOSE)
    xiamiBoard.OLEDclear()
    xiamiBoard.OLEDshowUserText("Motor CW", 0, 0)
    basic.pause(5000)
    led.plot(1, 0)
    pins.servoSetPulse(AnalogPin.P8, 1100)
    basic.pause(5000)
    led.plot(2, 0)
    pins.servoSetPulse(AnalogPin.P8, 1200)
    basic.pause(5000)
    led.plot(3, 0)
    led.plot(3, 1)
    pins.servoSetPulse(AnalogPin.P8, 1500)
    xiamiBoard.OLEDclear()
    xiamiBoard.OLEDshowUserText("Motor Stop", 0, 0)
    basic.pause(5000)
    led.plot(0, 1)
    xiamiBoard.setRelay(RELAYVERSION.V2, RELAY.DISCON)
    xiamiBoard.OLEDclear()
    xiamiBoard.OLEDshowUserText("Motor CCW", 0, 0)
    pins.servoSetPulse(AnalogPin.P8, 1700)
    basic.pause(5000)
    pins.servoSetPulse(AnalogPin.P8, 1800)
    led.plot(1, 1)
    basic.pause(5000)
    pins.servoSetPulse(AnalogPin.P8, 1900)
    led.plot(2, 1)
    basic.pause(5000)
    basic.clearScreen()
})
