xiamiBoard.initXiaMiBoard()
xiamiBoard.OLEDclear()
xiamiBoard.setRelay(RELAYVERSION.V1, RELAY.CLOSE)
xiamiBoard.OLEDshowUserText("Relay ON", 0, 0)
xiamiBoard.LED(0, 0, 1)
basic.showIcon(IconNames.Yes)
basic.pause(1000)
xiamiBoard.setRelay(RELAYVERSION.V1, RELAY.DISCON)
xiamiBoard.OLEDshowUserText("Relay OFF", 0, 0)
xiamiBoard.LED(1, 0, 0)
basic.showIcon(IconNames.No)
basic.pause(1000)
xiamiBoard.OLEDclear()
basic.showIcon(IconNames.Heart)
basic.forever(function () {
	
})
